// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package coralnpu

import chisel3._
import chisel3.util._
import common.Fp32

// Floating-point operation types (matching RISC-V F/D extension opcodes)
object FpuOptype extends ChiselEnum {
  val FpuAdd, FpuSub, FpuMul, FpuDiv, FpuSqrt,
      FpuFma, FpuFnma, FpuFms, FpuFnms,
      FpuFlt, FpuFle, FpuFeq, FpuFmax, FpuFmin,
      FpuFcvtSW, FpuFcvtSWU, FpuFcvtWS, FpuFcvtWUS,
      FpuFcvtSL, FpuFcvtLWS, FpuFsgnj, FpuFsgnjn, FpuFsgnjx,
      FpuFmvXW, FpuFmvWX = Value
}

// Floating-point CSR (control/status register)
class FloatCsr extends Bundle {
  val frm    = UInt(3.W)  // rounding mode
  val fflags = UInt(5.W)  // exception flags: NV, DZ, OF, UF, NX
}

// Command sent to the FPU
class FpuCommand extends Bundle {
  val optype = FpuOptype()
  val waddr  = UInt(5.W)   // destination FP register address
  val ina    = new Fp32    // first  FP operand
  val inb    = new Fp32    // second FP operand
  val inc    = new Fp32    // third  FP operand (addend for FMA)
  val rs1    = UInt(32.W)  // integer operand (FCVT, FMV)
  val frm    = UInt(3.W)   // per-instruction rounding mode override
}

// Result produced by the FPU
class FpuResult extends Bundle {
  val addr      = UInt(5.W)   // destination register address (echoed from command)
  val bits      = new Fp32    // FP result
  val intResult = UInt(32.W)  // integer result (for FCVT-to-int, FMV.X.W)
  val fflags    = UInt(5.W)   // exception flags generated by this operation
  val isInt     = Bool()       // true when the result should write an integer register
}

// Bundle that groups the FPU command/result interfaces
class FpuInterface extends Bundle {
  val cmd    = Flipped(Valid(new FpuCommand))
  val output = Decoupled(new FpuResult)
}
