#!/bin/bash
# harden.sh — Remove Bazel build cache artifacts that encode the green implementation.
#
# After the count stage runs tests with the green source, the Bazel output_base
# contains compiled objects and cached actions from the green implementation.
# If left in the final image, an agent could exploit these to pass tests without
# implementing any code.
#
# Hardening categories:
#   Category 1: Generated C headers from RTL (e.g., *_regs.h generated by reggen)
#     These encode register layouts derived from .hjson files.
#   Category 2: Compiled .o/.a files and test binaries from the green source C code.
#     The compiled dif_uart.o etc. encode the firmware implementation.
#   Category 3: Test logs and results from the warm run.
#
# What we KEEP: compiled toolchain artifacts (Clang, Python interpreter) that
# don't encode project-specific implementation. These speed up the agent's build.

set -euo pipefail

BAZEL_OUT="${HOME}/.cache/bazel/_bazel_builder"

if [ ! -d "${BAZEL_OUT}" ]; then
    echo "No bazel output dir found at ${BAZEL_OUT}, nothing to harden."
    exit 0
fi

echo "=== Hardening Bazel cache ==="

# Find the actual output_base (there's a hash-named subdir)
OUTPUT_BASE=$(find "${BAZEL_OUT}" -maxdepth 1 -type d | tail -1)
echo "Output base: ${OUTPUT_BASE}"

if [ -z "${OUTPUT_BASE}" ] || [ "${OUTPUT_BASE}" = "${BAZEL_OUT}" ]; then
    echo "No output_base subdirectory found, skipping."
    exit 0
fi

EXECROOT="${OUTPUT_BASE}/execroot/lowrisc_opentitan"
CACHE="${OUTPUT_BASE}/cache"

# Category 1: Remove generated C/C++ headers produced from green RTL/hjson
# These are in the bazel-out directories for the cc_library targets
find "${OUTPUT_BASE}" -name "*_regs.h" -delete 2>/dev/null || true
find "${OUTPUT_BASE}" -name "dif_*_autogen.h" -delete 2>/dev/null || true
find "${OUTPUT_BASE}" -name "dif_*_autogen.c" -delete 2>/dev/null || true

# Category 2: Remove compiled objects from project source files (not toolchain)
# Target the bazel-out directory for build artifacts
BAZEL_BIN="${OUTPUT_BASE}/execroot/lowrisc_opentitan/bazel-out"
if [ -d "${BAZEL_BIN}" ]; then
    # Remove object files compiled from project source (not third-party)
    find "${BAZEL_BIN}" -name "*.o" \
        \( -path "*/sw/device/*" -o -path "*/hw/*" \) \
        -delete 2>/dev/null || true
    find "${BAZEL_BIN}" -name "*.a" \
        \( -path "*/sw/device/*" \) \
        -delete 2>/dev/null || true
    # Remove test binaries (they encode the compiled test + impl)
    find "${BAZEL_BIN}" -name "*_unittest" -type f -executable -delete 2>/dev/null || true
    find "${BAZEL_BIN}" -name "*_test" -type f -executable -delete 2>/dev/null || true
    echo "Category 2: Removed compiled objects from project source."
fi

# Category 3: Remove test logs and cached test results from the warm run
find "${OUTPUT_BASE}" -name "test.log" -delete 2>/dev/null || true
find "${OUTPUT_BASE}" -name "test.xml" -delete 2>/dev/null || true
find "${OUTPUT_BASE}" -name "*.log" -path "*/test_logs/*" -delete 2>/dev/null || true
# Remove the action cache entries for project-specific build actions
# (These encode which actions were run with the green source)
if [ -d "${CACHE}" ]; then
    # Clear the action cache - forces recompilation but not re-download
    rm -rf "${CACHE:?}/action_cache" 2>/dev/null || true
    echo "Category 3: Cleared test logs and action cache."
fi

echo "=== Hardening complete ==="

# Report remaining cache size
du -sh "${OUTPUT_BASE}" 2>/dev/null || true
